---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(process)d-%(filename)s %(name)s %(levelname)s %(message)s"
        datefmt: '%Y-%m-%d  %H:%M:%S %a'

handlers:
    by_pid_file_handler:
        class: logger.RotatingFileHandlerByPID
        level: DEBUG
        formatter: simple
        filename: /data/ebox/wavegate/log/system.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8
    time_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /data/ebox/wavegate/log/system.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8
loggers:
    main:
        level: INFO
        handlers: [time_handler]
        propagate: no
    
root:
    level: INFO
    handlers: [time_handler]
