log_map = {'/net-web/auth/account_phone_pwd_login': "系统登录-账号登录",
           '/net-web/vidicon/getLiveRecordList': "实时视频", '/net-web/control/getEmergencyItems': "告警记录-列表",
           '/net-web/control/getEmergencyDetailInfo': "告警记录-详情",
           '/net-web/advise/addWebhookDelivery': "webhook-新增",
           '/net-web/advise/updateWebhookDelivery': "webhook-修改",
           '/net-web/advise/deleteWebhookDelivery': "webhook-删除", '/net-web/advise/addSmsDelivery': "短信投递-新增",
           '/net-web/advise/updateSmsDelivery': "短信投递-修改", '/net-web/advise/deleteSmsDelivery': "短信投递-删除",
           '/net-web/controltask/addControlTaskInsightModelAlgorithm': "布控任务-添加模型",
           '/net-web/controltask/addControlTaskPersons': "布控任务-添加人员",
           '/net-web/controltask/addControlTaskCameras': "布控任务-添加设备",
           '/net-web/controltask/addControlTask': "布控任务-新增",
           '/net-web/controltask/modifyControlTask': "布控任务-编辑",
           '/net-web/controltask/modifyControlTaskIsActive': "布控任务-开关",
           '/net-web/controltask/deleteControlTask': "布控任务-删除",
           '/net-web/controltask/queryControlTaskList': "布控任务-列表",
           '/net-web/vidicon/saveCameraEdit': "摄像机-添加", '/net-web/vidicon/updateCameraEdit': "摄像机-编辑",
           '/net-web/vidicon/deleteCameraEdit': "摄像机-删除", '/net-web/position/batchaddposition': "位置-新增",
           '/net-web/position/updateposition': "位置-编辑", '/net-web/position/delposition': "位置-删除",
           '/net-web/vidicon/saveEdgeService': "算法服务器-新增",
           '/net-web/vidicon/updateEdgeService': "算法服务器-编辑",
           '/net-web/vidicon/deleteEdgeService': "算法服务器-删除",
           '/net-web/vidicon/edgServiceBindCamera': "算法服务器-配置摄像机",
           '/net-web/persongroupmanage/addPersonnelGroup': "分组列表-新增",
           '/net-web/persongroupmanage/modifyPersonnelGroup': "分组列表-编辑",
           '/net-web/persongroupmanage/deletePersonnelGroup': "分组列表-删除",
           '/net-web/persongroupmanage/getPersonnelGroupList': "分组列表-列表",
           '/net-web/persongroupmanage/getPersonnelGroupInfo': "分组列表-详情",
           '/net-web/persongroupmanage/modifyPersonnelByGroupId': "分组列表-编辑人员",
           '/net-web/persongroupmanage/getPersonnelByGroupId': "分组列表-查询人员",
           '/net-web/personmanage/addPerson': "人脸库-新增",
           '/net-web/personmanage/validPersonImage': "人脸库-图片校验",
           '/net-web/personmanage/modifyPerson': "人脸库-编辑",
           '/net-web/personmanage/deletePersonnelData': "人脸库-删除",
           '/net-web/personmanage/addPersonBatch': "人脸库-批量添加",
           '/net-web/personmanage/getPersonList': "人脸库-列表",
           '/net-web/personmanage/downloadPersonList': "人脸库-导出",
           '/net-web/personmanage/getPersonDetailgetPersonDetail': "人脸库-详情",
           '/net-web/personmanage/getPersonCount': "人脸库-数量统计",
           '/net-web/auth/add_department_info': "部门管理-添加",
           '/net-web/auth/update_department_info': "部门管理-编辑",
           '/net-web/auth/delete_department_info': "部门管理-删除",
           '/net-web/auth/set_department_user': "部门管理-设置部门成员", '/net-web/auth/add_user': "账号管理-新增",
           '/net-web/auth/edit_user': "账号管理-编辑", '/net-web/auth/del_user': "账号管理-删除",
           '/net-web/auth/add_role_info': "角色管理-新增", '/net-web/auth/update_role_info': "角色管理-编辑",
           '/net-web/auth/delete_role_info': "角色管理-删除"}

